// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4cd91572-981e-43a6-bff5-15633f997189",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_taukgNPb0",
    "aws_user_pools_web_client_id": "o5kq1bt0424200pobgeuqaqb4",
    "oauth": {},
    "aws_user_files_s3_bucket": "s3newbucket-test",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
